version: '3'
services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: beautiful_wordcloud
      MYSQL_USER: wordcloud_user
      MYSQL_PASSWORD: torncloud
      MYSQL_DATABASE: wordcloudstore
  octoweb:
    build: .
    volumes: # For dev purpose
     - .:/code # For Dev Purpose: Allows to reload and display the fresh new code.
    links:
      - mysql
    ports:
     - "8888:8888"
